# Timeout time for query request
timeout: 2000 # In milliseconds

# Interval for updating query information
update: 1200 # In ticks

# Servers for query
servers:
  zeqa:                 # Server name
    address: "zeqa.net" # Server address
    port: 19132         # Server port
  nethergames:
    address: "play.nethergames.org"
    port: 19132